# Generated by Django 3.1.3 on 2021-02-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authkeys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthKeys',
        ),
    ]
