# Generated by Django 3.1.3 on 2021-02-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
