# Generated by Django 3.1.3 on 2021-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210227_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('street', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('house', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('flat', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('user', models.ManyToManyField(to='users.User')),
            ],
        ),
    ]
