# Generated by Django 3.1.3 on 2021-02-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='comment',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
