# Generated by Django 3.0.7 on 2021-04-19 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        ('users', '0011_auto_20210227_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(max_length=200)),
                ('bonus_used', models.IntegerField(blank=True, default=None, null=True)),
                ('delivery_method', models.IntegerField(default=1)),
                ('payment_method', models.IntegerField(default=1)),
                ('delivery_discount_use', models.BooleanField(default=False)),
                ('current_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('current_phone', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('discount', models.IntegerField()),
                ('from_amount', models.IntegerField(blank=True, default=None, null=True)),
                ('usage_type', models.CharField(choices=[('single', 'Один раз на каждого пользователя'), ('multiple', 'Множество раз на каждого')], default='single', max_length=50)),
                ('active', models.BooleanField()),
                ('categories', models.ManyToManyField(blank=True, null=True, to='products.Category')),
                ('products', models.ManyToManyField(blank=True, null=True, to='products.Product')),
                ('users', models.ManyToManyField(blank=True, null=True, to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=50)),
                ('delivery', models.CharField(choices=[('courier', 'Доставка курьером'), ('byclient', 'Самовывоз')], default='courier', max_length=200)),
                ('address', models.CharField(default='', max_length=1000)),
                ('payment', models.CharField(choices=[('cart', 'Картой курьеру'), ('cash', 'Наличными')], default='cash', max_length=200)),
                ('bonus_gained', models.IntegerField(blank=True, default=0, null=True)),
                ('bonus_used', models.IntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='in_progress', max_length=100)),
                ('delivery_discount_use', models.BooleanField(default=False)),
                ('user_append_bonus', models.BooleanField(default=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.Coupon')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.User')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Order')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Favoriteitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_id', models.IntegerField(default=None)),
                ('favorite', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Favorite')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.Coupon'),
        ),
    ]
