# Generated by Django 3.0.7 on 2021-04-19 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='', max_length=300)),
                ('name', models.CharField(default='', max_length=300)),
                ('imgsrc', models.ImageField(default='', upload_to='static/images/products')),
                ('display_priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('description', models.CharField(default='', max_length=2000)),
                ('imgsrc', models.ImageField(upload_to='static/images/products')),
                ('display_priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('single', 'single'), ('variative', 'variative')], default='single', max_length=50)),
                ('size', models.CharField(blank=True, choices=[('Маленькая (25 см)', 'small'), ('Средняя (30 см)', 'medium'), ('Большая (35 см)', 'large')], default=None, max_length=200, null=True)),
                ('testo', models.CharField(blank=True, choices=[('traditional', 'Традиционное'), ('tonkoe', 'Тонкое')], default=None, max_length=200, null=True)),
                ('name', models.CharField(default='', max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('ves', models.CharField(default='', max_length=300)),
                ('description', models.CharField(default='', max_length=2000)),
                ('imgsrc', models.ImageField(default='', upload_to='static/images/products')),
                ('display_priority', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_value', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.AttributeBase')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('attribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.Product')),
            ],
            bases=('products.attribute',),
        ),
    ]
