# Generated by Django 3.0.7 on 2021-04-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributebase',
            name='lvl',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='internal_value',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
