# Generated by Django 3.0.7 on 2021-04-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210424_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product',
            field=models.ManyToManyField(related_name='attributes', to='products.Product'),
        ),
    ]
