# Generated by Django 3.0.7 on 2021-04-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210424_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='testo',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='imgsrc',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ves',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
