# Generated by Django 3.0.7 on 2021-05-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210506_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='display_priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
