# Generated by Django 3.0.7 on 2021-05-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210506_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display_priority',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
